jobs:
- name: immospider
  command: curl -H "X-API-KEY: ${env.API_KEY}" http://127.0.0.1:7860/trigger
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  onFailure:
    report:
      telegram:
        token: ${env.TELEGRAM_API_TOKEN}
        chat_id: ${env.TELEGRAM_CHAT_ID}
        message: "Spider run failed!"
  onSuccess:
    report:
      telegram:
        token: ${env.TELEGRAM_API_TOKEN}
        chat_id: ${env.TELEGRAM_CHAT_ID}
        message: "Spider run completed successfully! (No item data available for detailed message.)"
