jobs:
  - name: immospider
    command: curl -H "X-API-KEY: ${env.API_KEY}" ${env.API_URL:-http://127.0.0.1:8000}/trigger
    schedule: "*/15 * * * *"
    concurrencyPolicy: Forbid
    onFailure:
      report:
        telegram:
          token: ${env.TELEGRAM_API_TOKEN}
          chat_id: ${env.TELEGRAM_CHAT_ID}
          message: "Spider run failed!"
